version: "3.7"
services:
# - "./dumps:/var/dumps" - This is my local volume
  mysql-server:
    image: mysql
    command: 
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - "./dumps:/var/dumps"
    environment: 
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=Password

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-5.0-latest
    ports:
      - "10052:10052"

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-5.0-latest
    ports: 
      - 10051:10051
    volumes:
      - "./dumps:/var/dumps"
    links:
      - mysql-server:mysql-server
      - zabbix-java-gateway:zabbix-java-gateway
    environment: 
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - ZBX_JAVAGATEWAY="zabbix-java-gateway"
    depends_on:
      - mysql-server
      - zabbix-java-gateway

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.0-latest
    ports:
      - 8081:8080
      - 8443:8443
    links:
      - mysql-server:mysql-server
      - zabbix-server:zabbix-server
    volumes:
      - "./dumps:/var/dumps"
    environment: 
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
    depends_on:
      - mysql-server
      - zabbix-server
  
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-5.0-latest
    ports: 
      - 10050:10050
    volumes:
      - "./dumps:/var/dumps"
    links:
      - zabbix-server:zabbix-server

